name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - master

# 連續 push 多次，只會留下最新那次部署在跑，舊的會被自動取消。
concurrency:
  group: deploy-production
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4
        with:
          lfs: true  # Ensure Git LFS files are fetched
          fetch-depth: 0  # Fetch all history for all branches and tags
      
      - name: Git LFS Pull
        run: |
          git lfs install
          git lfs pull
      
      # 防呆：如果把 pointer 誤 commit 進來，直接讓 CI fail
      - name: Fail build if any LFS pointer appears in repo
        run: |
          if grep -R --include="*.{png,svg,jpg,jpeg,gif,webp}" -n "version https://git-lfs.github.com/spec/v1" . ; then
            echo "ERROR: Found LFS pointer file(s). Real binary not present."
            exit 1
          fi
          
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci --no-audit --no-fund --progress=false

      - name: Build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: npx vue-cli-service build --report --report-json
      
      # 僅上傳 dist/ 到 EC2 的 web 根目錄
      - name: Upload dist to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "${{ secrets.TARGET_DIR }}/dist"
          strip_components: 1
      
      # 重啟 PM2（若是純前端靜態檔，其實只要 Nginx 即可，不一定要 PM2）
      - name: Restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 10m
          script: |
            cd ${{ secrets.TARGET_DIR }}
            pm2 startOrReload ecosystem.config.js --only chrislo-web || true
            pm2 save || true