name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4
        with:
          lfs: true  # Ensure Git LFS files are fetched
          fetch-depth: 0  # Fetch all history for all branches and tags
      
      - name: Git LFS Pull
        run: |
          git lfs install
          git lfs pull
      
      # 防呆：如果有人把 pointer 誤 commit 進來，直接讓 CI fail
      - name: Fail build if any LFS pointer appears in repo
        run: |
          if grep -R --include="*.{png,svg,jpg,jpeg,gif,webp}" -n "version https://git-lfs.github.com/spec/v1" . ; then
            echo "ERROR: Found LFS pointer file(s). Real binary not present."
            exit 1
          fi

      - name: Deploy to Server 
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
      
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd ${{ secrets.TARGET_DIR }}/deploy
            chmod +x sync.sh
            bash ./sync.sh